services:
  quark-portal:
    image: ghcr.io/jsemolik/quark-portal:latest
    container_name: quark-portal
    restart: unless-stopped
    environment:
      - APP_PORT=8080
      - APP_ENV=production
    ports:
      - "8080:8080"
    volumes:
      - quark-portal-data:/var/lib/quark-portal
volumes:
  quark-portal-data:
